config/routes.rb
PresentersApp::Application.routes.draw do
  resources :preferences

  resources :users

  resources(:selections, only: :index) { resources :selections, except: :show }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/preference.rb
class Preference < ActiveRecord::Base
  belongs_to :user
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  selectable
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :preferences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  unless Rails.application.config.consider_all_requests_local
    rescue_from CanCan::AccessDenied do |exception|
      # Notify errbit if you would like to:
      # Airbrake.notify(exception)
      render 'public/403', status: 403, layout: 'none'
    end
  end

end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  def index
    @preferences = Preference.all
  end

  def show
  end

  def new
    @preference = Preference.new
  end

  def edit
  end

  # POST /preferences
  def create
    @preference = Preference.new(preference_params)

    if @preference.save
      redirect_to @preference, notice: 'Preference was successfully created.'
    else
      render :new
    end
  end

  def update
    if @preference.update(preference_params)
      redirect_to @preference, notice: 'Preference was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @preference.destroy
    redirect_to preferences_url, notice: 'Preference was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def preference_params
      params.require(:preference).permit(:name)
    end
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_filter :parent_finder

  def index
    if @parent
      @selections = @parent.children
    else
      @selections = Selection.roots
    end
  end

  def new
    @selection = @parent.children.new
  end

  def edit
    @selection = @parent.children.find(params[:id])
  end

  def create
    @selection = @parent.children.new(params[:selection])

    if @selection.save
      redirect_to selection_selections_path(@parent), notice: 'Selection was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @selection = Selection.find(params[:id])

    if @selection.update_attributes(params[:selection])
      redirect_to selection_selections_path(@parent), notice: 'Selection was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @selection = Selection.find(params[:id])
    @selection.destroy

    redirect_to selections_url
  end

  private
  def parent_finder
    @parent = Selection.find_by_id(params[:selection_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = UserPresenter.new(@user)
  end

  def new
    @user = User.new
  end

  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
  def selector selection
    if selection.leaf?
      link_to_unless selection.parent.try(:is_system), selection.name, edit_selection_selection_path(@parent, selection)
    else
      link_to selection.name, selection_selections_path(selection)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{"name"=>"viewport", "content"=>"width=device-width", "initial-scale"=>1}
    = csrf_meta_tag
    = javascript_include_tag :application
    = stylesheet_link_tag :application, media: 'all'

    /[if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js'
  %body
    .row
      .col-md-12
        .container
          .row
            = render 'navigation'
          .row
            - if alert
              %p.alert= alert
            - if notice
              %p.notice= notice
          .row
            = yield

app/views/preferences/_form.html.haml
= form_for @preference, html: { "role" =>"form", class: "form-horizontal"} do |f|
  - if @preference.errors.any?
    #error_explanation
      %h2= "#{pluralize(@preference.errors.count, 'error')} prohibited this preference from being saved:"
      %ul
        - @preference.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-md-2 control-label'
    .col-md-6
      = f.text_field :name, class: 'form-control input-sm'
  .form-group
    .col-md-6.col-md-offset-2
      = f.submit 'Save', class: 'btn btn-success btn-sm'

app/views/preferences/edit.html.haml
.page-header
  %h1 Editing preference
.row
  .col-md-12
    = render 'form'
    = link_to 'Cancel', preference_path(@preference), id: :cancel_edit_preference_link, class: 'btn btn-sm btn-warning'

app/views/preferences/index.html.haml
.page-header
  %h1 Listing preferences

.row
  .col-md-12
    %table.table.table-striped
      %tr
        %th Name


      - @preferences.each do |preference|
        %tr
          %td= link_to preference.name, preference_path(preference)

    %br

    = link_to 'New Preference', new_preference_path, id: :new_preference_link, class: 'btn btn-primary btn-sm'

app/views/preferences/new.html.haml
.page-header
  %h1 New preference
.row
  .col-md-12
    = render 'form'
    = link_to 'Cancel', preferences_path, id: :cancel_new_preference_link, class: 'btn btn-sm btn-warning'

app/views/preferences/show.html.haml
.row
  .col-md-12

    %p
      %b Name:
      = @preference.name
  
    = link_to 'Edit', edit_preference_path(@preference), id: :edit_preference_link, class: 'btn btn-sm btn-primary'

app/views/selections/_form.html.haml
= form_for ([@parent, @selection]), html: {class: 'form-horizontal'} do |f|
  - if @selection.errors.any?
    #error_explanation
      %h2= "#{pluralize(@selection.errors.count, "error")} prohibited this selection from being saved:"
      %ul
        - @selection.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :name
    .controls
      = f.text_field :name
  .control-group
    = f.label :parent
    .controls
      = link_to @selection.parent, selection_selections_path(@selection.parent)
  .control-group
    = f.label :system_code
    .controls
      = f.text_field :system_code, :readonly => !@selection.new_record?
  .control-group
    = f.label :position_value
    .controls
      = f.text_field :position_value
  .control-group
    = f.label :is_default
    .controls
      = f.check_box :is_default
  .control-group
    = f.label :archived
    .controls
      = f.check_box :archived

  .form-actions
    = f.submit 'Save Changes', :class => 'btn-primary'
    = link_to 'Cancel', selection_selections_path(@parent), :class => 'btn'

app/views/selections/edit.html.haml
.edit-details
  %h3 Editing Selection
  = render 'form'

app/views/selections/index.html.haml
- if @parent
  %h3
    = "Children of #{@parent.name}"
    = link_to ' (Back)', selections_path
  = link_to 'New Selection', new_selection_selection_path(@parent), :class => 'btn create' unless @parent.is_system
- else
  %h3
    Selections
%table.data.table-striped{:width => "100%"}
  %tr
    %th Name
    %th Position value
    %th Is default
    %th Archived at
    %th System code
  - if @selections.size == 0
    %tr.no-records
      %td{:colspan => "6"}
        %p No records to display.
  - @selections.each do |selection|
    %tr
      %td= selector selection
      %td= selection.position_value
      %td= selection.is_default
      %td= selection.archived_at
      %td= selection.system_code

app/views/selections/new.html.haml
.new-details
  %h3 New Selection
  = render 'form'

app/views/users/_form.html.haml
= form_for @user, html: { "role" =>"form", class: "form-horizontal"} do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, 'error')} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    .col-md-6.col-md-offset-2
      = f.submit 'Save', class: 'btn btn-success btn-sm'

app/views/users/edit.html.haml
.page-header
  %h1 Editing user
.row
  .col-md-12
    = render 'form'
    = link_to 'Cancel', user_path(@user), id: :cancel_edit_user_link, class: 'btn btn-sm btn-warning'

app/views/users/index.html.haml
.page-header
  %h1 Listing users

.row
  .col-md-12
    %table.table.table-striped
      %tr


      - @users.each do |user|
        %tr

    %br

    = link_to 'New User', new_user_path, id: :new_user_link, class: 'btn btn-primary btn-sm'

app/views/users/new.html.haml
.page-header
  %h1 New user
.row
  .col-md-12
    = render 'form'
    = link_to 'Cancel', users_path, id: :cancel_new_user_link, class: 'btn btn-sm btn-warning'

app/views/users/show.html.haml
.page-header
  %h1 #{@user.full_name_with_title}
.row
  .col-md-12
    .row
      .col-md-12
        = @user.avatar_link
    .row
      .col-md-12
        %p
          Preferences:
          = @user.preference_names
    .row
      .col-md-12
        %p
          Description:
          = @user.description

    = link_to 'Edit', edit_user_path(@user), id: :edit_user_link, class: 'btn btn-sm btn-primary'